#!/bin/bash

PATH=/usr/sbin:/usr/bin:/sbin:/bin

prog=$(basename $0)
exec=$(which $prog)

if [ -n "${exec}" ]; then
  exec ${exec} $@
else
  USER_UID=$(id -u)
  USER_GID=$(id -g)

  XSOCK=/tmp/.X11-unix
  XAUTH=/tmp/.docker.xauth
  xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f ${XAUTH} nmerge -

  # remove stopped containers
  echo "Removing stopped containers..."
  for c in $(docker ps -a -q)
  do
    image="$(docker inspect -f {{.Config.Image}} ${c})"
    if [ "${image}" == "sameersbn/browser-box:latest" ]; then
      running=$(docker inspect -f {{.State.Running}} ${c})
      if [ "${running}" != "true" ]; then
        docker rm "${c}" >/dev/null
      fi
    fi
  done

  echo "Starting ${prog}..."
  touch ${XAUTH}
  docker run -d \
    --cap-add=SYS_ADMIN \
    --env="USER_UID=${USER_UID}" \
    --env="USER_GID=${USER_GID}" \
    --env="DISPLAY" \
    --env="XAUTHORITY=${XAUTH}" \
    --volume=${XSOCK}:${XSOCK} \
    --volume=${XAUTH}:${XAUTH} \
    --volume=/run/user/${USER_UID}/pulse:/run/pulse \
    sameersbn/browser-box:latest $(basename $0) $@ >/dev/null
fi
