#!/bin/bash

PATH=/usr/sbin:/usr/bin:/sbin:/bin

prog=$(basename $0)
exec=$(which $prog)

if [ -n "${exec}" ]; then
  exec ${exec} $@
else
  USER_UID=$(id -u)
  USER_GID=$(id -g)

  # remove stopped containers
  echo "Removing stopped containers..."
  for c in $(docker ps -a -q)
  do
    image="$(docker inspect -f {{.Config.Image}} ${c})"
    if [ "${image}" == "sameersbn/browser-bundle:latest" ]; then
      running=$(docker inspect -f {{.State.Running}} ${c})
      if [ "${running}" != "true" ]; then
        docker rm "${c}" >/dev/null
      fi
    fi
  done

  echo "Starting ${prog}..."
  docker run -d \
    --env="USER_UID=${USER_UID}" \
    --env="USER_GID=${USER_GID}" \
    --env="DISPLAY=${DISPLAY}" \
    --volume=/tmp/.X11-unix:/tmp/.X11-unix \
    --volume=/run/user/${USER_UID}/pulse:/run/pulse \
    sameersbn/browser-bundle:latest $(basename $0) $@ >/dev/null
fi
